import 'package:powersync/powersync.dart';

/// Client-side SQLite schema for PowerSync.
///
/// Rules:
/// - Every **synced** table includes [organization_id] (tenant non-negotiable).
/// - Indexes support org-scoped list queries used offline.
/// - Column sets should stay aligned with Sync Streams + Postgres;
///   regenerate from PowerSync Dashboard when streams stabilize.
///
/// PowerSync always provides a text `id` column; do not redefine it.
/// Infrastructure foundation — not a full production column audit.
final Schema peekePowerSyncSchema = Schema([
  Table(
    'organization_members',
    [
      Column.text('organization_id'),
      Column.text('user_id'),
      Column.text('role'),
      Column.text('title'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    indexes: [
      Index('om_org', [IndexedColumn('organization_id')]),
      Index('om_user', [IndexedColumn('user_id')]),
    ],
  ),
  Table(
    'organizations',
    [
      Column.text('name'),
      Column.text('slug'),
      Column.text('status'),
      Column.text('testing_until'),
      Column.text('review_note'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
  ),
  Table(
    'clients',
    [
      Column.text('organization_id'),
      Column.text('name'),
      Column.text('code'),
      Column.text('site_name'),
      Column.text('location'),
      Column.text('contact'),
      Column.text('location_coords'),
      Column.text('phone'),
      Column.text('email'),
      Column.text('billing_address'),
      Column.text('account_manager'),
      Column.text('account_type'),
      Column.integer('sla_hours'),
      Column.integer('is_active'),
      Column.text('notes'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    indexes: [
      Index('clients_org', [IndexedColumn('organization_id')]),
    ],
  ),
  Table(
    'systems',
    [
      Column.text('organization_id'),
      Column.text('client_id'),
      Column.text('name'),
      Column.text('code'),
      Column.text('type'),
      Column.text('model'),
      Column.text('serial_number'),
      Column.real('capacity'),
      Column.text('capacity_unit'),
      Column.text('barcode'),
      Column.text('site_name'),
      Column.text('status'),
      Column.text('notes'),
      Column.text('client_name'),
      Column.text('client_location'),
      Column.text('client_site'),
      Column.text('installation_date'),
      Column.text('registration_date'),
      Column.real('fuel_tank_capacity'),
      Column.real('initial_hour_meter'),
      Column.real('initial_energy_meter'),
      Column.text('operation_type'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    indexes: [
      Index('systems_org', [IndexedColumn('organization_id')]),
      Index('systems_client', [IndexedColumn('client_id')]),
    ],
  ),
  Table(
    'work_requests',
    [
      Column.text('organization_id'),
      Column.text('wr_number'),
      Column.text('client_id'),
      Column.text('system_id'),
      Column.text('client_name'),
      Column.text('client_site'),
      Column.text('system_type'),
      Column.text('system_model'),
      Column.text('system_serial'),
      Column.text('job_type'),
      Column.text('priority'),
      Column.text('requested_by'),
      Column.text('description'),
      Column.text('fault_description'),
      Column.text('notes'),
      Column.text('status'),
      Column.integer('needs_procurement'),
      Column.text('reviewed_by'),
      Column.text('review_notes'),
      Column.text('reviewed_at'),
      Column.text('work_order_id'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    indexes: [
      Index('wr_org', [IndexedColumn('organization_id')]),
      Index('wr_status', [IndexedColumn('status')]),
    ],
  ),
  Table(
    'work_orders',
    [
      Column.text('organization_id'),
      Column.text('wo_number'),
      Column.text('work_request_id'),
      Column.text('client_id'),
      Column.text('system_id'),
      Column.text('client_name'),
      Column.text('client_site'),
      Column.text('system_type'),
      Column.text('system_model'),
      Column.text('system_serial'),
      Column.text('job_type'),
      Column.text('priority'),
      Column.text('requested_by'),
      Column.text('description'),
      Column.text('fault_description'),
      Column.text('notes'),
      Column.text('status'),
      Column.integer('needs_procurement'),
      Column.text('assigned_technician'),
      Column.text('completed_by'),
      Column.text('completed_at'),
      Column.text('approved_by'),
      Column.text('approved_at'),
      Column.text('approval_notes'),
      Column.text('cancelled_by'),
      Column.text('cancelled_at'),
      Column.text('cancel_notes'),
      Column.text('created_at'),
      Column.text('updated_at'),
    ],
    indexes: [
      Index('wo_org', [IndexedColumn('organization_id')]),
      Index('wo_status', [IndexedColumn('status')]),
    ],
  ),
  // work_order_parts / work_order_events: enable with streams after parents proven.
]);
